In [7]:
import pandas as pd
#df = pd.read_csv('pokemon_data.csv')
df = pd.read_csv('pokemon_data.txt', delimiter='\t')
print(dftxt)
#print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [51]:
#reading headers
df.columns
# read each column
#print(df['Name'][0:5])
#print(df[['Name', 'Type 1', 'HP']])
#read each row
#print(df.iloc[1])
#print(df.iloc[2,1])
#for index, row in df.iterrows():
#    print(index, row['Name'])

#read each specific location(r,c)

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Total             405
Name: 1, dtype: object

In [49]:
#finding data that isnt just interger base.. its based on more tetual information 
df.loc[df['Type 1'] == "Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [30]:
#this is for another one
df.loc[df['Type 2'] == "Flying"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
15,12,Butterfree,Bug,Flying,60,45,50,90,80,70,1,False
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
734,666,Vivillon,Bug,Flying,80,52,50,90,50,89,6,False
771,701,Hawlucha,Fighting,Flying,78,92,75,74,63,118,6,False
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True

In [32]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [33]:
#so this sorts the value by name
df.sort_values('Name')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [48]:
#the false makes it tpo decend when its actually supposed to be ascending 
df.sort_values('Name', ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True,600
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False,420
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False,245
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False,330
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False,510
...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False,565
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False,465
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False,310
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False,594
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False,494

In [39]:
#this is for combing .. if you wnat both to accend 
#df.sort_values(['Type 1', 'HP'], ascending=True)
#if you want one to decend and the other to acend
df.sort_values(['Type 1', 'HP'], ascending=[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

In [53]:
#always cross check you dont want to be caught on the wrong side 
#df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
#to delete a column
#df = df.drop(columns=['Total'])
df['Total'] = df.iloc[:, 4:10].sum(axis=1)

df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [62]:
cols = list(df.columns)
df = df[cols[0:4] + [cols[-1]]+cols[4:12]]
df.head(5)

,#,Name,Type 1,Type 2,Speed,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def
0,1,Bulbasaur,Grass,Poison,45,1,False,318,45,49,49,65,65
1,2,Ivysaur,Grass,Poison,60,1,False,405,60,62,63,80,80
2,3,Venusaur,Grass,Poison,80,1,False,525,80,82,83,100,100
3,3,VenusaurMega Venusaur,Grass,Poison,80,1,False,625,80,100,123,122,120
4,4,Charmander,Fire,NaN,65,1,False,309,39,52,43,60,50

In [69]:
#saving data frames
#df.to_csv('modified.csv',index=False)
df.to_excel('modified.xlsx',index=False)

In [79]:
# you can use and or "or" to seperate the conditions
new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)]
new_df = new_df.reset_index(drop=True, inplace=True)

In [84]:
# the ~ sign is used to drop all the megas instead
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Speed,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def
3,3,VenusaurMega Venusaur,Grass,Poison,80,1,False,625,80,100,123,122,120
7,6,CharizardMega Charizard X,Fire,Dragon,100,1,False,634,78,130,111,130,85
8,6,CharizardMega Charizard Y,Fire,Flying,100,1,False,634,78,104,78,159,115
12,9,BlastoiseMega Blastoise,Water,NaN,78,1,False,630,79,103,120,135,115
19,15,BeedrillMega Beedrill,Bug,Poison,145,1,False,495,65,150,40,15,80
23,18,PidgeotMega Pidgeot,Normal,Flying,121,1,False,579,83,80,80,135,80
71,65,AlakazamMega Alakazam,Psychic,NaN,150,1,False,590,55,50,65,175,95
87,80,SlowbroMega Slowbro,Water,Psychic,30,1,False,590,95,75,180,130,80
102,94,GengarMega Gengar,Ghost,Poison,130,1,False,600,60,65,80,170,95
124,115,KangaskhanMega Kangaskhan,Normal,NaN,100,1,False,590,105,125,100,60,100
137,127,PinsirMega Pinsir,Bug,Flying,105,1,False,600,65,155,120,65,90
141,130,GyaradosMega Gyarados,Water,Dark,81,1,False,640,95,155,109,70,130
154,142,AerodactylMega Aerodactyl,Rock,Flying,150,1,False,615,80,135,85,70,95
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,130,1,True,780,106,190,100,154,100
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,140,1,True,780,106,150,70,194,120
168,154,Meganium,Grass,NaN,80,2,False,525,80,82,100,83,100
196,181,AmpharosMega Ampharos,Electric,Dragon,45,2,False,610,90,95,105,165,110
224,208,SteelixMega Steelix,Steel,Ground,30,2,False,610,75,125,230,55,95
229,212,ScizorMega Scizor,Bug,Steel,75,2,False,600,70,150,140,65,100
232,214,HeracrossMega Heracross,Bug,Fighting,75,2,False,600,80,185,115,40,105
248,229,HoundoomMega Houndoom,Dark,Fire,115,2,False,600,75,90,90,140,90
268,248,TyranitarMega Tyranitar,Rock,Dark,71,2,False,700,100,164,150,95,120
275,254,SceptileMega Sceptile,Grass,Dragon,145,3,False,630,70,110,75,145,85
279,257,BlazikenMega Blaziken,Fire,Fighting,100,3,False,630,80,160,80,130,80
283,260,SwampertMega Swampert,Water,Ground,70,3,False,635,100,150,110,95,110
306,282,GardevoirMega Gardevoir,Psychic,Fairy,100,3,False,618,68,85,65,165,135
327,302,SableyeMega Sableye,Dark,Ghost,20,3,False,480,50,85,125,85,115
329,303,MawileMega Mawile,Steel,Fairy,50,3,False,480,50,105,125,55,95
333,306,AggronMega Aggron,Steel,NaN,50,3,False,630,70,140,230,60,80
336,308,MedichamMega Medicham,Fighting,Psychic,100,3,False,510,60,100,85,80,85
339,310,ManectricMega Manectric,Electric,NaN,135,3,False,575,70,75,80,135,80
349,319,SharpedoMega Sharpedo,Water,Dark,105,3,False,560,70,140,70,110,65
354,323,CameruptMega Camerupt,Fire,Ground,20,3,False,560,70,120,100,145,105
366,334,AltariaMega Altaria,Dragon,Fairy,80,3,False,590,75,110,110,110,105
387,354,BanetteMega Banette,Ghost,NaN,75,3,False,555,64,165,75,93,83
393,359,AbsolMega Absol,Dark,NaN,115,3,False,565,65,150,60,115,60
397,362,GlalieMega Glalie,Ice,NaN,100,3,False,580,80,120,80,120,80
409,373,SalamenceMega Salamence,Dragon,Flying,120,3,False,700,95,145,130,120,90
413,376,MetagrossMega Metagross,Steel,Psychic,110,3,False,700,80,145,150,105,110
418,380,LatiasMega Latias,Dragon,Psychic,110,3,True,700,80,100,120,140,150
420,381,LatiosMega Latios,Dragon,Psychic,110,3,True,700,80,130,100,160,120
426,384,RayquazaMega Rayquaza,Dragon,Flying,115,3,True,780,105,180,100,180,100
476,428,LopunnyMega Lopunny,Normal,Fighting,135,4,False,580,65,136,94,54,96
494,445,GarchompMega Garchomp,Dragon,Ground,92,4,False,700,108,170,115,120,95
498,448,LucarioMega Lucario,Fighting,Steel,112,4,False,625,70,145,88,140,70
511,460,AbomasnowMega Abomasnow,Grass,Ice,30,4,False,594,90,132,105,132,105
527,475,GalladeMega Gallade,Psychic,Fighting,110,4,False,618,68,165,95,65,115
591,531,AudinoMega Audino,Normal,Fairy,50,5,False,545,103,60,126,80,126
796,719,DiancieMega Diancie,Rock,Fairy,110,6,True,700,50,160,110,160,110

In [91]:
import re
# if you want the pi to be in beginning  only ^
df.loc[df['Name'].str.contains('pi[a-z]*', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Speed,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def
13,10,Caterpie,Bug,NaN,45,1,False,195,45,30,35,20,20
20,16,Pidgey,Normal,Flying,56,1,False,251,40,45,40,35,35
21,17,Pidgeotto,Normal,Flying,71,1,False,349,63,60,55,50,50
22,18,Pidgeot,Normal,Flying,101,1,False,479,83,80,75,70,70
23,18,PidgeotMega Pidgeot,Normal,Flying,121,1,False,579,83,80,80,135,80
30,25,Pikachu,Electric,NaN,90,1,False,320,35,55,40,50,50
42,37,Vulpix,Fire,NaN,65,1,False,299,38,41,40,50,65
76,70,Weepinbell,Grass,Poison,55,1,False,390,65,90,50,85,45
84,78,Rapidash,Fire,NaN,105,1,False,500,65,100,70,80,80
136,127,Pinsir,Bug,NaN,85,1,False,500,65,125,100,55,70
137,127,PinsirMega Pinsir,Bug,Flying,105,1,False,600,65,155,120,65,90
181,167,Spinarak,Bug,Poison,30,2,False,250,40,60,40,40,40
186,172,Pichu,Electric,NaN,60,2,False,205,20,40,15,35,35
189,175,Togepi,Fairy,NaN,20,2,False,245,35,20,65,40,65
202,187,Hoppip,Grass,Flying,50,2,False,250,35,35,40,35,55
219,204,Pineco,Bug,NaN,15,2,False,290,50,65,90,35,35
239,221,Piloswine,Ice,Ground,50,2,False,450,100,100,80,60,60
266,247,Pupitar,Rock,Ground,51,2,False,410,70,84,70,65,70
345,316,Gulpin,Poison,NaN,40,3,False,302,70,43,53,43,53
357,326,Grumpig,Psychic,NaN,80,3,False,470,80,45,65,90,110
358,327,Spinda,Normal,NaN,60,3,False,360,60,60,60,60,60
359,328,Trapinch,Ground,NaN,10,3,False,290,45,100,45,45,45
390,357,Tropius,Grass,Flying,51,3,False,460,99,68,83,72,87
438,393,Piplup,Water,NaN,40,4,False,314,53,51,53,61,56
463,416,Vespiquen,Bug,Flying,40,4,False,474,70,80,102,80,102
488,440,Happiny,Normal,NaN,30,4,False,220,100,5,5,15,65
490,442,Spiritomb,Ghost,Dark,35,4,False,485,50,92,108,92,108
501,451,Skorupi,Poison,Bug,65,4,False,330,40,50,90,30,55
502,452,Drapion,Poison,Dark,95,4,False,500,70,90,110,60,75
557,498,Tepig,Fire,NaN,45,5,False,308,65,63,45,45,45
558,499,Pignite,Fire,Fighting,55,5,False,418,90,93,55,70,55
578,519,Pidove,Normal,Flying,43,5,False,264,50,55,50,36,30
596,536,Palpitoad,Water,Ground,69,5,False,384,75,65,55,65,55
716,648,MeloettaPirouette Forme,Normal,Fighting,128,5,False,600,100,128,90,77,77
718,650,Chespin,Grass,NaN,38,6,False,313,56,61,65,48,45

In [101]:
#this changes the fire in type 1 to flammer 
df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flammer'
df

,#,Name,Type 1,Type 2,Speed,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Type 1,Type 2
0,1,Bulbasaur,Grass,Poison,45,1,False,318,45,49,49,65,65,Flax,Flax
1,2,Ivysaur,Grass,Poison,60,1,False,405,60,62,63,80,80,Flax,Flax
2,3,Venusaur,Grass,Poison,80,1,False,525,80,82,83,100,100,Flax,Flax
3,3,VenusaurMega Venusaur,Grass,Poison,80,1,False,625,80,100,123,122,120,Flax,Flax
4,4,Charmander,Flammer,NaN,65,1,False,309,39,52,43,60,50,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,6,True,600,50,100,150,100,150,NaN,NaN
796,719,DiancieMega Diancie,Rock,Fairy,110,6,True,700,50,160,110,160,110,NaN,NaN
797,720,HoopaHoopa Confined,Psychic,Ghost,70,6,True,600,80,110,60,150,130,NaN,NaN
798,720,HoopaHoopa Unbound,Psychic,Dark,80,6,True,680,80,160,60,170,130,NaN,NaN
799,721,Volcanion,Flammer,Water,70,6,True,600,80,110,120,130,90,NaN,NaN

In [102]:

#this changes the poison in type 1 to flax
df.loc[df['Type 2'] == 'Poison', 'Type 2'] = 'Flax'
df

,#,Name,Type 1,Type 2,Speed,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Type 1,Type 2
0,1,Bulbasaur,Grass,Flax,45,1,False,318,45,49,49,65,65,Flax,Flax
1,2,Ivysaur,Grass,Flax,60,1,False,405,60,62,63,80,80,Flax,Flax
2,3,Venusaur,Grass,Flax,80,1,False,525,80,82,83,100,100,Flax,Flax
3,3,VenusaurMega Venusaur,Grass,Flax,80,1,False,625,80,100,123,122,120,Flax,Flax
4,4,Charmander,Flammer,NaN,65,1,False,309,39,52,43,60,50,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,6,True,600,50,100,150,100,150,NaN,NaN
796,719,DiancieMega Diancie,Rock,Fairy,110,6,True,700,50,160,110,160,110,NaN,NaN
797,720,HoopaHoopa Confined,Psychic,Ghost,70,6,True,600,80,110,60,150,130,NaN,NaN
798,720,HoopaHoopa Unbound,Psychic,Dark,80,6,True,680,80,160,60,170,130,NaN,NaN
799,721,Volcanion,Flammer,Water,70,6,True,600,80,110,120,130,90,NaN,NaN